name: End-to-end tests 🧪
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use a versão Node.js adequada

      - name: Install NPM dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.js
